### ISSUE TITLE
Use Sensors for Pool Waiting?

### ISSUE THREAD

**Issue by kemics** [Toloka/airflow-provider-toloka#1]
Airflow has a concept of so-called [sensors](https://airflow.apache.org/docs/apache-airflow/stable/_api/airflow/sensors/index.html?highlight=sensor#module-airflow.sensors) . This is a cheap way to wait for meeting some condition

Current implementation with `while pool.is_open():` takes airflow worker slot until pool finishes. If the number of concurrently running crowdsourcing project is high then this is quite expensive

Internally, we have implementation like this (not perfect but works well):

```python
    def __wait_until_pool_done_sensor__(self, key: str):
        def __wait_until_pool_done_sensor_internal__(**kwargs):
            pool_id = kwargs["ti"].xcom_pull(key=key)
            return self.toloka_hook.is_pool_closed(pool_id)

        return __wait_until_pool_done_sensor_internal__

    def create_wait_until_pool_done_sensor(
        self,
        task_id: str,
        xcom_pool_id_key: str = "",
        poke_interval=300,
        on_failure_callback=None,
    ) -> PythonSensor:
        if xcom_pool_id_key == "":
            xcom_pool_id_key = f"{self.name}_created_pool_id"

        return PythonSensor(
            task_id=task_id,
            python_callable=self.__wait_until_pool_done_sensor__(xcom_pool_id_key),
            mode="reschedule",
            poke_interval=poke_interval,
            on_failure_callback=on_failure_callback,
        )
```

**Comment by Pocoder** [comment]
Thanks for your proposal. 
We will loot at this functionality and most likely use similar solution. Or you can become contributor and make pull request =)

By the way, how you pass objects like projects or tasks between airflow tasks. Do you use custom x-com backend or pass ids and then get objects in next task?

**Comment by Pocoder** [comment]
`wait_pool` is sensor now
