### ISSUE TITLE
Create PR to review for Astronomer Registry

### ISSUE THREAD

**Issue by fhoda** [Toloka/airflow-provider-toloka#5]
Hi @Pocoder , This is Faisal from Astronomer. Can you create a PR so that I can leave comments, discuss, and track updates? This will make the Registry submission process move a little bit smoother.  Thank you!

**Comment by Pocoder** [comment]
Hello @fhoda. Can you explain how and which exactly PR do you want me to open?

**Comment by fhoda** [comment]
It can be something really simple, like a new branch in this repo with a small edit to a comment or something that gets a PR back to main.

**Comment by Pocoder** [comment]
https://github.com/Toloka/airflow-provider-toloka/pull/6
